name: CosmelonPlugin
version: '1.0'
date:
main: me.cosmelon.cosmelonplugin.CosmelonPlugin
api-version: '1.20'
softdepend:
  - DiscordSRV
commands:
  playerhide:
    description: Hides players
    usage: /playerhide
  playershow:
    description: Shows hidden players
    usage: /playershow
  reloadpack:
    description: Fresh copy of the resourcepack
    usage: /reloadresources
  colorblind:
    description: Turns on the colorblind resourcepack
    usage: /colorblind
  whitelist:
    description: UUID whitelist
    usage: /whitelist -help
    permission: CosmelonPlugin.whitelist
  memory:
    description: Server RAM info.
    usage: /memory [-usage]
    permission: CosmelonPlugin.memusage
  fixmusic:
    description: Restarts the current music track
    usage: /fixmusic
  reafycheck:
    description: Does a ready check
    usage: /reafycheck
    permission: CosmelonPlugin.memusage
  nick:
    description: Set a player nickname
    usage: /nick
    permission: CosmelonPlugin.nick

